# This is a basic workflow to help you get started with Actions

name: armTemplateDeploy

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Provision new resource group
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 615d1e7e-a44b-4606-a534-fdd1045ffa68
          region: Central India
          parameters: location="Central India"
            resourceGroupName=rg-githubactions
          template: ./arm-templates/resourcegroup.json
          deploymentMode: Complete

      - name: Create storage account
        uses: azure/arm-deploy@v1
        id: storageDeployed
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          #subscriptionId: 615d1e7e-a44b-4606-a534-fdd1045ffa68
          #region: Central India
          parameters: sku=Standard_LRS
            storageAccountName=kksoni1982
            location="West India"
          template: ./arm-templates/storageaccount.json
          deploymentMode: Complete

      - run: echo ${{ steps.storageDeployed.outputs.blobURI}}
